language: node_js
node_js:
- stable
deploy:
- provider: elasticbeanstalk
  edge: true
  app: Two2er
  env: LowCost-env
  bucket_name: elasticbeanstalk-us-east-2-120103986746
  region: us-east-2
  access_key_id: AKIAIQI5PG7PW7ZEOQ7A
  secret_access_key:
    secure: owBM1JnDwgON7M7jniLs97tmtG6bU9z0Fg5ns4ZIi6vrYilTjz2P8wGfSGUp1D5cLokO5/DdFCezDJ2VR2805eyDwLfE3BgdJi7bwUM9iUmJ9MXzu2fGZjTNkcWGAckeVOKgJhaREM/0C/gIDGCFM0GoPWI/O4Gmi3bOs9BRWZmD3MsZ5Xrt6ODrnU2uzIbtVGCpXWZ26GshV6VIFvTAeZJafRXeHXoQF41m0fLNzjxJ0PhDsF+88y2RYL5AbgOHPSrw2DTVWIaAhRY+lBGMzIykALA3Muo3C4nXcMvMpkMIvvfnhIT1vSmc32/2qQc1sdBFu3OsN/S3Wj/APu3+Wn+Smx6uJwTl8bpVRO6R1M32ox+BUozWPfhdRKoHYMK229twW728JgC2eYT5FTWlkEoE6gIYE5mgGgcPJ2y+IPR07O/+xflY+RXSB/1KA9NzGTeGSeSH0UIWyl8wDBVVb/Vmqsk0dtR0oBD0GscCoeh6CDXOCgVBtcR8pPB1G9H5q4tdAgFdDRW7xyzQWDoE7tbpxiXDw9iP/XPZA3eF1lCjd/ULvFBErcIFMqIcBP1SSXo+CkRg62FbNjST1KTjOSDUHTzphfPACpCDmcf24hJXcrT9yWHsWEetCS8eVTUpjkCgP4gazygg6dIBdKgVMtQmYQlKUfFZemaYXe4Tsr8=
  on:
    repo: ajscilingo/two2er-nodejs
    branch: dev
