language: node_js
node_js:

deploy:
- provider: elasticbeanstalk
  edge: true
  app: Two2er
  env: LowCost-env
  bucket_name: elasticbeanstalk-us-east-2-120103986746
  region: us-east-2
  access_key_id: {{AWS_ACCESS_KEY}}
  secret_access_key:
    secure: {{AWS_SECRET_KEY}}
  on:
    repo: ajscilingo/two2er-nodejs
    branch: dev
